site_name: WallPanel Documentation
site_url: https://j-a-n.github.io/lovelace-wallpanel
repo_url: https://github.com/j-a-n/lovelace-wallpanel
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.features
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.hightlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: teal
      accent: teal

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: teal
      accent: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quick-start.md
  - Configuration: configuration.md
  - Browser Mod: browser-mod.md
  - Screensaver:
    - Screensaver: screensaver.md
    - Media Sources: media-sources.md
    - Media Info: media-info.md
    - Info Box: info-box.md
  - Styling: styling.md
  - Motion Detection: camera-motion-detection.md
  - Other Configuration: other-configuration.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Cedits: credits.md
  - Additional Resources: additional-resources.md

