# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
# https://github.com/pages-themes/leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: jekyll-theme-leap-day